[package]
name = "lexgen_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
lexgen = { path = "/home/omer/rust/lexgen/crates/lexgen" }
lexgen_util = { path = "/home/omer/rust/lexgen/crates/lexgen_util" }

[profile.dev.package.lexgen]
opt-level = 3
